### ISSUE TITLE
how can I generate the input data?

### ISSUE THREAD

**Issue by hu1060** [PietroMsn/Functional-skeleton-transfer#1]
Hi,
I downloaded the code, but I don‘t know how to get the input data such as 'basicmodel_m_lbs.mat'. 
Do these data need to be preprocessed by other code or something else?

**Comment by PietroMsn** [comment]
hi, the data in that file are a translation in a .mat of the .pkl of SMPL model that you can find at https://smpl.is.tue.mpg.de/ , the original file is a python .pkl
we use smpl model for experiments because they provide a joint regressor
